[versions]
agp = "8.13.0"
android-material = "1.13.0"
androidx-activity = "1.11.0"
androidx-annotation = "1.9.1"
androidx-appcompat = "1.7.1"
androidx-compose-bom = "2025.10.00"
androidx-constraintlayout = "2.2.1"
androidx-core = "1.17.0"
androidx-datastore = "1.1.7"
androidx-fragment = "1.8.9"
androidx-lifecycle = "2.9.4"
androidx-navigation = "2.9.5"
androidx-recyclerview = "1.4.0"
androidx-test-core = "1.7.0"
androidx-test-espresso = "3.7.0"
androidx-test-junit = "1.3.0"
androidx-test-uiautomator = "2.3.0"
bouncycastle = "1.82"
google-kotlin-ksp = "2.2.20-2.0.2"
gradle-nexus-publish = "2.0.0"
hilt = "2.57.2"
hilt-navigation-compose = "1.3.0"
junit = "4.13.2"
kotlin = "2.2.20"
kotlinx-coroutines-android = "1.10.2"
logback-android = "3.0.0"
protobuf-gradle-plugin = "0.9.5"
protobuf-java = "4.32.1"
sl4j = "2.0.17"

[libraries]
android-material = { group = "com.google.android.material", name = "material", version.ref = "android-material" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx-activity" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidx-annotation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" } # versioned by androidx-compose-bom
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" } # versioned by androidx-compose-bom
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" } # versioned by androidx-compose-bom
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" } # versioned by androidx-compose-bom
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" } # versioned by androidx-compose-bom
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" } # versioned by androidx-compose-bom
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" } # versioned by androidx-compose-bom
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "androidx-datastore" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidx-recyclerview" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidx-test-core" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-test-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidx-test-junit" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidx-test-core" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-core" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidx-test-uiautomator" }
bouncycastle-bcprov-jdk18on = { group = "org.bouncycastle", name = "bcprov-jdk18on", version.ref = "bouncycastle" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
hilt-testing-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
logback-android = { group = "com.github.tony19", name = "logback-android", version.ref = "logback-android" }
protobuf-java = { group = "com.google.protobuf", name = "protobuf-java", version.ref = "protobuf-java" }
sl4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "sl4j" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
androidx-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "androidx-navigation" }
google-kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "google-kotlin-ksp" }
gradle-nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "gradle-nexus-publish" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-gradle-plugin" }