name: React-Native CI

on:
  push:
    branches: [ main, next ]
    paths: [ '.github/**', 'fakewalletreact/**', 'js/**' ]
  pull_request:
    branches: [ main, next ]
    paths: [ '.github/**', 'fakewalletreact/**', 'js/**' ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5

      - name: set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: 'fakewalletreact/package.json' # note - node engine should match between fakewalletreact/ and js/
          cache: yarn
          cache-dependency-path: 'fakewalletreact/yarn.lock' # note - this only caches for fakewalletreact/, not js/

      - name: set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v5

      - name: '[js] Install yarn dependencies'
        working-directory: 'js/'
        run: yarn install --frozen-lockfile
      - name: '[js] Lint'
        working-directory: 'js/'
        run: yarn lint
        continue-on-error: true # TODO: fix all lint issues and remove this line
      - name: '[js] Build'
        working-directory: 'js/'
        run: yarn build

      - name: '[fakewalletreact] Install yarn dependencies'
        working-directory: 'fakewalletreact/'
        run: yarn install --frozen-lockfile
      - name: '[fakewalletreact] Lint'
        working-directory: 'fakewalletreact/'
        run: yarn lint
        continue-on-error: true # TODO: fix all lint issues and remove this line
      - name: '[fakewalletreact] Build'
        working-directory: 'fakewalletreact/'
        run: yarn android:build
